
package com.umss.xy.ws.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.8
 * 2018-06-07T17:32:06.975+08:00
 * Generated source version: 2.7.8
 */

@WebFault(name = "getPersonDataFault", targetNamespace = "http://ws.xy.umss.com/")
public class GetPersonDataFault extends Exception {
    
    private com.umss.xy.ws.PersonalDataFault getPersonDataFault;

    public GetPersonDataFault() {
        super();
    }
    
    public GetPersonDataFault(String message) {
        super(message);
    }
    
    public GetPersonDataFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetPersonDataFault(String message, com.umss.xy.ws.PersonalDataFault getPersonDataFault) {
        super(message);
        this.getPersonDataFault = getPersonDataFault;
    }

    public GetPersonDataFault(String message, com.umss.xy.ws.PersonalDataFault getPersonDataFault, Throwable cause) {
        super(message, cause);
        this.getPersonDataFault = getPersonDataFault;
    }

    public com.umss.xy.ws.PersonalDataFault getFaultInfo() {
        return this.getPersonDataFault;
    }
}
