package com.umss.xy.ws.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2018-06-07T17:32:07.095+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://ws.xy.umss.com/v1", name = "MyPersonalDataServicePort")
@XmlSeeAlso({com.umss.xy.ws.ObjectFactory.class})
public interface MyPersonalDataServicePort {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getPersonDataResponse", targetNamespace = "http://ws.xy.umss.com/", partName = "getPersonDataResponse")
    @WebMethod(action = "getPerson")
    public com.umss.xy.ws.GetPersonDataResponse getPerson(
        @WebParam(partName = "getPersonData", name = "getPersonData", targetNamespace = "http://ws.xy.umss.com/")
        com.umss.xy.ws.GetPersonData getPersonData
    ) throws GetPersonDataFault;

    @RequestWrapper(localName = "getAllCars", targetNamespace = "http://ws.xy.umss.com/", className = "com.umss.xy.ws.GetAllCars")
    @WebMethod(action = "getAllCars")
    @ResponseWrapper(localName = "getAllCarsResponse", targetNamespace = "http://ws.xy.umss.com/", className = "com.umss.xy.ws.GetAllCarsResponse")
    public void getAllCars(
        @WebParam(name = "msisdn", targetNamespace = "http://ws.xy.umss.com/")
        java.lang.String msisdn,
        @WebParam(mode = WebParam.Mode.OUT, name = "responseHeader", targetNamespace = "http://ws.xy.umss.com/")
        javax.xml.ws.Holder<com.umss.xy.ws.ResponseHeader> responseHeader,
        @WebParam(mode = WebParam.Mode.OUT, name = "responseBody", targetNamespace = "http://ws.xy.umss.com/")
        javax.xml.ws.Holder<com.umss.xy.ws.ResponseBody> responseBody
    ) throws GetAllCarsFault;

    @RequestWrapper(localName = "getMyCar", targetNamespace = "http://ws.xy.umss.com/", className = "com.umss.xy.ws.GetMyCar")
    @WebMethod(action = "getMyCar")
    @ResponseWrapper(localName = "getMyCarResponse", targetNamespace = "http://ws.xy.umss.com/", className = "com.umss.xy.ws.GetMyCarResponse")
    public void getMyCar(
        @WebParam(name = "msisdn", targetNamespace = "http://ws.xy.umss.com/")
        java.lang.String msisdn,
        @WebParam(mode = WebParam.Mode.OUT, name = "responseHeader", targetNamespace = "http://ws.xy.umss.com/")
        javax.xml.ws.Holder<com.umss.xy.ws.ResponseHeader> responseHeader,
        @WebParam(mode = WebParam.Mode.OUT, name = "responseBody", targetNamespace = "http://ws.xy.umss.com/")
        javax.xml.ws.Holder<com.umss.xy.ws.ResponseBody> responseBody
    ) throws GetMyCarFault;
}
