package com.umss.xy.ws.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2018-06-07T17:32:07.142+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "MyPersonalDataService", 
                  wsdlLocation = "file:/F:/2018/my-personal-data-service/src/main/resources/wsdl/my-personal-data-service.wsdl",
                  targetNamespace = "http://ws.xy.umss.com/v1") 
public class MyPersonalDataService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.xy.umss.com/v1", "MyPersonalDataService");
    public final static QName MyPersonalDataServicePort = new QName("http://ws.xy.umss.com/v1", "MyPersonalDataServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/F:/2018/my-personal-data-service/src/main/resources/wsdl/my-personal-data-service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MyPersonalDataService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/F:/2018/my-personal-data-service/src/main/resources/wsdl/my-personal-data-service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MyPersonalDataService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyPersonalDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyPersonalDataService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyPersonalDataService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyPersonalDataService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyPersonalDataService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MyPersonalDataServicePort
     */
    @WebEndpoint(name = "MyPersonalDataServicePort")
    public MyPersonalDataServicePort getMyPersonalDataServicePort() {
        return super.getPort(MyPersonalDataServicePort, MyPersonalDataServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyPersonalDataServicePort
     */
    @WebEndpoint(name = "MyPersonalDataServicePort")
    public MyPersonalDataServicePort getMyPersonalDataServicePort(WebServiceFeature... features) {
        return super.getPort(MyPersonalDataServicePort, MyPersonalDataServicePort.class, features);
    }

}
